version: '3'
services:

  db:
    image: postgres:alpine
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    ports:
      - 16379:6379

  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/app
    environment:
      DEBUG: express:*
      SECRET_KEY: deadbeef
      DATABASE_URL: postgresql://postgres@db/postgres
      REDIS_URL: redis://redis/
    command: npm run dev
    depends_on:
      - db
      - redis
