version: '3'
services:

  redis:
    image: redis:alpine

  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/app
    environment:
      DEBUG: express:*
      SECRET_KEY: deadbeef
      REDIS_URL: redis://redis/
    command: npm run dev
    depends_on:
      - redis
